[Settings]
3GLTEHandover = false
MaxNonDataMode = none

radioInterface = 1.4
emptyPinQuery = false
useDataProfiles = true
mmsDataProfileId = 1001
rilRequestOnSetUdub = 13

[slot1]
path = /ril_0
slot = 0
